beibei_shopping/beibei_shopping/urls.py
from django.conf.urls import url

from . import views

app_name = "users"

urlpatterns = [
    url(r"^login/$",views.user_login,name="user_login"),
    url(r"^register/$",views.user_register,name="user_register"),
    url(r"^logout/$",views.user_logout,name="user_logout"),
    url(r"^userinfo/$",views.user_info,name="user_info"),

]

beibei_shopping/goods/urls.py
from django.conf.urls import url

from . import views

app_name = "goods"


urlpatterns = [
    url(r'^add/$',views.add,name="add")
    # url(r'')
]

beibei_shopping/store/urls.py
from django.conf.urls import url

from . import views

app_name = "store"


urlpatterns = [
    url(r"^add/$",views.add,name="add"),
    url(r"^list/$",views.list,name="list"),
    url(r"^update/(?P<s_id>\d+)/$",views.update,name="update"),
    url(r"^detail/(?P<s_id>\d+)/$",views.detail,name="detail"),
    url(r"^change/(?P<s_id>\d+)/(?P<status>\d+)/$",views.change,name="change"),

]

beibei_shopping/store/models.py
from django.db import models
from django.contrib.auth.models import User



class Store(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255,unique=True,verbose_name="店铺名称")
    cover = models.ImageField(upload_to="static/images/store",default="static/images/store/beibei.png")
    intro = models.TextField(verbose_name="店铺描述")
    # 开店时间
    opener_time = models.DateTimeField(auto_now_add=True,verbose_name="开店时间")
    # 0表示正常营业，1表示暂停营业，2表示永久关闭
    status = models.IntegerField(default=0,verbose_name="店铺状态")
    user = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name="店铺所属的用户")

beibei_shopping/store/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_GET

from . import models

@login_required
def add(request):
    '''增加店铺'''
    if request.method == "GET":
        return render(request,"store/add.html",{})
    else:
        name = request.POST["name"].strip()
        intro = request.POST["intro"].strip()
        try:
            cover = request.FILES["cover"]
            store = models.Store(name=name,intro=intro,cover=cover,user=request.user)
            store.save()
        except:
            store = models.Store(name=name,intro=intro,user=request.user)
        store.save()
        # return redirect(reverse("store:detail",kwargs={"s_id":store.id}))
        return redirect(reverse("store:detail", kwargs={"s_id": store.id}))


@require_GET
@login_required
def list(request):
    '''店铺列表'''
    stores = models.Store.objects.filter(user=request.user,status__in=[0,1])
    return render(request,"store/list.html",{"stores":stores})


@login_required
def update(request,s_id):
    '''修改店铺'''
    if request.method == "GET":
        store = models.Store.objects.get(pk=s_id)
        return render(request,"store/update.html",{"store":store})
    else:
        name = request.POST["name"].strip()
        intro = request.POST["intro"].strip()

        store = models.Store.objects.get(pk=s_id)
        store.name = name
        store.intro = intro
        try:
            cover = request.FILES["cover"]
            store.cover = cover
        except:
            pass
        store.save()

        return redirect(reverse("store:detail",kwargs={"s_id":store.id}))



@require_GET
@login_required
def detail(request,s_id):
    '''店铺详情'''
    store = models.Store.objects.get(pk=s_id)
    return render(request,"store/detail.html",{"store":store})


@require_GET
@login_required
def change(request,s_id,status):
    '''修改店铺状态'''
    store = models.Store.objects.get(id=s_id)
    store.status = int(status)
    store.save()
    if store.status == 2:
        return redirect(reverse("store:list"))
    else:
        return render(request, "store/detail.html", {"store": store})

beibei_shopping/store/templates/store/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>增加店铺</title>
</head>
<body>
    <h1>开业大吉！</h1>
    <form action="{% url 'store:add' %}" method="post">
        {% csrf_token %}
        店铺名称：<input type="text" name="name"><br>
        店铺封面：<input type="file" name="cover"><br>
        店铺描述：<textarea name="intro"></textarea><br>
        <input type="submit" value="开业大吉">
    </form>
</body>
</html>

beibei_shopping/store/templates/store/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>店铺详情</title>
</head>
<body>
    <h1>店铺详情</h1>
    <table>
        <tr>
            <td>店铺封面</td>
            <td><img src="/{{ store.cover }}" alt="123"></td>
        </tr>
        <tr>
            <td>店铺名称</td>
            <td>{{ store.name }}</td>
        </tr>
        <tr>
            <td>店铺状态</td>
            <td>
                {% if store.status == 0 %}
                    <p>正在营业</p>
                <a href="{% url 'store:change' store.id 1 %}">暂停营业</a>
                <a href="{% url 'store:change' store.id 2 %}">关闭店铺</a>
                {% elif store.status == 1 %}
                    <p>暂停营业</p>
                <a href="{% url 'store:change' store.id 0 %}">开始营业</a>
                <a href="{% url 'store:change' store.id 2 %}">关闭店铺</a>

                {% endif %}
            </td>
        </tr>
        <tr>
            <td>操作</td>
            <td><a href="{% url 'store:update' store.id %}">修改店铺信息</a></td>
        </tr>
    </table>
</body>
</html>

beibei_shopping/store/templates/store/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>店铺列表</title>
</head>
<body>
<h1>店铺列表</h1>
<table border="1">
    {% for store in stores %}
    <tr>
        <td>店铺名称</td>
        <td>{{ store.name }}</td>
    </tr>
    <tr>
        <td>店铺封面</td>
        <td><img src="/{{store.cover}}" alt=""></td>
        <td>店铺描述</td>
        <td>{{ store.intro }}</td>
        <td><a href="{% url 'store:detail' store.id %}">查询详情</a></td>
    </tr>
    {% empty %}
    <tr>
        <td>您还没有店铺，赶紧去<a href="{% url 'store:add' %}">开店</a>吧</td>
    </tr>
    {% endfor %}

</table>

</body>
</html>

beibei_shopping/store/templates/store/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改店铺</title>
</head>
<body>
    <h1>修改店铺</h1>
    <form action="{% url 'store:update' store.id %}" method="post">
        {% csrf_token %}
        店铺名称：<input type="text" name="name" value="{{store.name}}"><br>
        店铺封面：<input type="file" name="cover" id="cover"><br>
        店铺描述：<textarea name="intro">{{store.intro}}</textarea><br>
        <input type="submit" value="修改店铺">
    </form>
</body>
</html>