beibei_shopping/beibei_shopping/urls.py
from django.conf.urls import url

from . import views

app_name = "users"

urlpatterns = [
    url(r"^login/$",views.user_login,name="user_login"),
    url(r"^register/$",views.user_register,name="user_register"),
    url(r"^logout/$",views.user_logout,name="user_logout"),
    url(r"^userinfo/$",views.user_info,name="user_info"),

]

beibei_shopping/goods/urls.py
from django.conf.urls import url

from . import views

app_name = "goods"


urlpatterns = [
    url(r'^add/$',views.add,name="add")
    # url(r'')
]

beibei_shopping/users/urls.py
from django.conf.urls import url

from . import views

app_name = "users"

urlpatterns = [
    url(r"^login/$",views.user_login,name="user_login"),
    url(r"^register/$",views.user_register,name="user_register"),
    url(r"^logout/$",views.user_logout,name="user_logout"),
    url(r"^userinfo/$",views.user_info,name="user_info"),

]

beibei_shopping/users/models.py
from django.db import models
from django.contrib.auth.models import User


class UserInfo(models.Model):
    id = models.AutoField(primary_key=True)
    nickname = models.CharField(max_length=255,unique=True,verbose_name="用户昵称")
    age = models.IntegerField(default=18,verbose_name="用户年龄")
    gender = models.CharField(max_length=10,default="男",verbose_name="用户性别")
    header = models.ImageField(upload_to="static/images/headers",default="static/images/headers/beibei.png",verbose_name="用户头像")
    phone = models.IntegerField(max_length=50,default=123456,verbose_name="用户手机号码")


    # 和系统内置的用户管理建立一对一的关系
    user = models.OneToOneField(User,on_delete=models.CASCADE)

beibei_shopping/users/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import reverse
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.contrib.auth import logout
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required

from . import models



def user_login(request):
    '''用户登录'''
    if request.method == "GET":
        try:
            next_url = request.GET["next"]
        except:
            next_url = "/"

        return render(request, "users/login.html", {"next_url":next_url})
    elif request.method == "POST":
        username = request.POST["username"].strip()
        password = request.POST["password"].strip()

        next_url = request.POST.get("next","/")

        # 验证码
        # code = request.POST["code"].strip()

        user = authenticate(username=username,password=password)
        if user is not None:
            if user.is_active:
                # 将验证通过的用户信息保存在request
                login(request,user)
                return redirect(next_url)
            else:
                return render(request, "users/login.html", {"msg": "您的账号已经被锁定，请联系管理员"})
        else:
            return render(request, "users/login.html", {"msg": "账号或者密码有误"})


def user_register(request):
    '''用户注册'''
    if request.method == "GET":
        return render(request,"users/register.html",{"msg":"请认真填写如下选项"})
    elif request.method == "POST":
        # 接受参数

        username = request.POST.get("username").strip()
        password = request.POST.get("password").strip()
        confirmpwd = request.POST.get("confirmpwd").strip()
        nickname = request.POST.get("nickname").strip()

        # 数据校验
        if len(username) < 1:
            return render(request,"users/register.html",{"msg":"用户名不能为空！！"})

        if len(password) < 6:
            return render(request,"users/register.html",{"msg":"密码长度不能小于6位！！"})

        if password != confirmpwd:
            return render(request,"users/register.html",{"msg":"两次密码不一致！！"})

        # 用户名是否重复
        try:
            User.objects.get(username=username)
            return render(request,"users/register.html",{"msg":"用户名重复！"})
        except:

            try:
                # 判断昵称是否重复
                models.UserInfo.objects.get(nickname=nickname)
                return render(request,"users/register.html",{"msg":"昵称重复！"})
            except:
                # 保存用户信息
                user = User.objects.create_user(username=username,password=password)
                user_info = models.UserInfo(nickname=nickname,user=user)
                user.save()
                user_info.save()
                return render(request,"users/login.html",{"msg":"用户注册成功"})



@login_required
def user_logout(request):
    '''注销用户'''
    logout(request)
    return render(request, "users/login.html", {"msg": "退出成功！"})


@login_required
def user_info(request):

    return render(request,"users/userinfo.html",{})

beibei_shopping/users/templates/users/login.html
<!DOCTYPE html>
<html>
	<head>
		{% load static %}
		<meta charset="UTF-8">
		<title>用户登录</title>
		<link rel="stylesheet" href="{% static 'css/style.css' %}" />
		<link rel="stylesheet" href="{% static 'css/login.css' %}" />
		<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/jquery.validate.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/form.js' %}" ></script>
		
	</head>
	<body>
		<div id="login_top">
			<ul class="login_top_left">
				<li class="login_top_left1"><a href="../mall.html"></a></li>
				<li class="login_top_left2">登录</li>
			</ul>
			
			<ul class="login_top_right">
				<li class="login_top_right1">100%正品</li>
				<li class="login_top_right2">一时达</li>
				<li class="login_top_right3">金牌客服</li>
			</ul>
		</div>

		<div id="login_center">
			<div class="login_center_left">
				<a href=""><img src="../images/login/0901denglutu.jpg" /></a>
			</div>
			
			<div class="login_center_right">
				<form id="login_form" action="{% url 'user:user_login' %}" method="post">
					{% csrf_token %}
					<!--账号输入框-->
					<div id="input_cell">
						<!--<label id="account_label" for="account">邮箱/手机号/用户名</label>-->
						<input class="username" name="username" id="account" type="text" placeholder="请输入用户名" />
						<span id="account_ok" class="ok"></span>
						<div id="account_error" class="error_text">
							<span class="error_V"></span>
							<span class="error_Prompt">键盘大写锁定已打开，请注意大小写</span>
						</div>
					</div>
					
					<!--密码输入框-->
					<div id="input_cell1">
						<!--<label id="pasword_label" for="passWord">请输入密码</label>-->
						<input name="password" id="passWord" type="password" placeholder="请输入密码" />
						<span id="passWord_ok" class="ok"></span>
						<div id="passWord_error" class="error_text">
							<span class="error_V"></span>
							<span class="error_Prompt">键盘大写锁定已打开，请注意大小写</span>
						</div>
					</div>
					
					<!--验证码输入框-->
					<div id="input_cell2">
						<!--<label id="verification_label" for="verification">请输入验证码</label>-->
						<input name="verificationCode" id="verification" type="text" placeholder="请输入验证码" />
						<span id="verification_ok" class="ok"></span>
						<div id="verification_error" class="error_text">
							<span class="error_V"></span>
							<span class="error_Prompt">键盘大写锁定已打开，请注意大小写</span>
						</div>
						
						<div id="img_code">
							<!--<img src="../images/login/yanZhengCodeNew.ashx.png" />-->
						</div>
						<a class="changeImg" href="javascript:;">看不清？换一张</a>
					</div>
					
					<!--记住用户名-->
					<div id="remember">
						<span class="remember_account">记住用户名</span>
						<a class="forget_password" href="">忘记密码？</a>
					</div>
					
					<!--登录-->
					<div id="login_cell">
						<input class="login_btn" type="submit" value="登录" />
						<a href="register.html" class="register_link">30秒注册»</a>
					</div>
				</form>
				
				<p id="otherWays">使用合作网站账号登录：</p>
				<a href="" class="way_weibo"></a>
				<a href="" class="way_QQ"></a>
				<a href="" class="way_zhi"></a>
			</div>
		</div>
		
		<div id="login_bottom">
			<p>			
				Copyright © 2018 北屋网(www.beiwu.com) 版权所有
				<a href="" target="_blank">京ICP备12022216号-2</a>
			</p>
			<p>北屋虽然好，但需克制使用信用卡</p>
		</div>
		
	</body>
</html>

beibei_shopping/users/templates/users/register.html
<!DOCTYPE html>
<html>
	<head>
		{% load static %}
		<meta charset="UTF-8">
		<title>用户注册</title>
		<link rel="stylesheet" href="/static/css/users/style.css">
		<link rel="stylesheet" href="/static/css/users/login.css">
		<link rel="stylesheet" href="/static/css/users/register.css">
		<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js" ></script>
		<script type="text/javascript" src="/static/js/style.js" ></script>
		<script type="text/javascript" src="/static/js/jquery.validate.min.js" ></script>
		<script type="text/javascript" src="/static/js/form.js" ></script>
	</head>
	<body>
		<div id="login_top">
			<ul class="login_top_left">
				<li class="login_top_left1"><a href="../mall.html"></a></li>
				<li class="login_top_left2">注册</li>
			</ul>
			
			<ul class="login_top_right">
				<li class="login_top_right1">100%正品</li>
				<li class="login_top_right2">同城一时达</li>
				<li class="login_top_right3">金牌客服</li>
			</ul>
		</div>
		
		<div id="login_center">
			<div class="login_center_left">
				<a href=""><img src="../images/login/0223xinrenzhuce.jpg" /></a>
			</div>
			
			<div class="login_center_right">
				<p id="goLogin">
					我已经注册，
					<a href="login.html">登录»</a>	
				</p>
				<form id="register_form" action="{% url 'users:user_register' %}" method="post">
					{% csrf_token %}
					<!--账号输入框-->
					<div id="input_cell">
						<!--<label id="account_label" for="account">请输入手机号</label>-->
						<input name="phonenum" id="account" type="text" placeholder="请输入用户名" />
						<span id="account_ok" class="ok"></span>
						<div id="account_error" class="error_text">
							<span class="error_V"></span>
							<span class="error_Prompt">键盘大写锁定已打开，请注意大小写</span>
						</div>
					</div>
					
					
					<!--验证码输入框-->
					<div id="input_cell1">
						<!--<label id="verification_label" for="verification">请输入验证码</label>-->
						<input id="verification" type="text" placeholder="请输入验证码"/>
						<span id="verification_ok" class="ok"></span>
						<div id="verification_error" class="error_text">
							<span class="error_V"></span>
							<span class="error_Prompt">键盘大写锁定已打开，请注意大小写</span>
						</div>
						<div id="img_code">
							<img src="../images/login/yanZhengCodeNew.ashx.png" />
						</div>
						<a class="changeImg" href="javascript:;">看不清？换一张</a>
					</div>
					
					<!--验证码输入框-->
					<div id="input_cell2">
						<!--<label id="verification_label" for="verification">请输入验证码</label>-->
						<input id="verification1" type="text" placeholder="请输入校证码"/>
						<span id="verification_ok1" class="ok"></span>
						<div id="verification_error1" class="error_text">
							<span class="error_V"></span>
							<span class="error_Prompt">键盘大写锁定已打开，请注意大小写</span>
						</div>
						
						<!--免费获取校验码-->
						<a class="getCheckCode">免费获取校验码</a>
					</div>
					
					<!--密码输入框-->
					<div id="input_cell3">
						<!--<label id="pasword_label" for="passWord">请输入密码</label>-->
						<input name="password" id="passWord" type="password" placeholder="请输入密码"  />
						<span id="passWord_ok" class="ok"></span>
						<div id="passWord_error" class="error_text">
							<span class="error_V"></span>
							<span class="error_Prompt">键盘大写锁定已打开，请注意大小写</span>
						</div>
					</div>
					
					
					<!--确认密码输入框-->
					<div id="input_cell4">
						<!--<label id="pasword_label" for="passWord">请输入确认密码</label>-->
						<input name="confirmpwd" id="passWord2" type="password" placeholder="请确认密码"  />
						<span id="passWord_ok1" class="ok"></span>
						<div id="passWord_error1" class="error_text">
							<span class="error_V"></span>
							<span class="error_Prompt">键盘大写锁定已打开，请注意大小写</span>
						</div>
					</div>
					
					<!--登录-->
					<div id="login_cell">
						<input class="register_btn" type="submit" value="同意协议并注册" />
					</div>
				</form>
				
				<p id="otherWays">
					<a href="" class="clause">《北屋网服务条款》</a>
				</p>
				
			</div>
		</div>
		
		<div id="login_bottom">
			<p>			
				Copyright © 2018 北屋网(www.beiwu.com) 版权所有
				<a href="" target="_blank">京ICP备12022216号-2</a>
			</p>
			<p>北屋虽然好，但需克制使用信用卡</p>
		</div>
		
	</body>
</html>