beibei_shopping/beibei_shopping/urls.py
from django.conf.urls import url

from . import views

app_name = "users"

urlpatterns = [
    url(r"^login/$",views.user_login,name="user_login"),
    url(r"^register/$",views.user_register,name="user_register"),
    url(r"^logout/$",views.user_logout,name="user_logout"),
    url(r"^userinfo/$",views.user_info,name="user_info"),

]

beibei_shopping/goods/urls.py
from django.conf.urls import url

from . import views

app_name = "goods"


urlpatterns = [
    url(r'^add/$',views.add,name="add")
    # url(r'')
]

beibei_shopping/store/urls.py
from django.conf.urls import url

from . import views

app_name = "store"


urlpatterns = [
    url(r"^add/$",views.add,name="add"),
    url(r"^list/$",views.list,name="list"),
    url(r"^update/(?P<s_id>\d+)/$",views.update,name="update"),
    url(r"^detail/(?P<s_id>\d+)/$",views.detail,name="detail"),
    url(r"^change/(?P<s_id>\d+)/(?P<status>\d+)/$",views.change,name="change"),

]

beibei_shopping/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
    <h1>项目首页</h1>
    <h1>{{msg}}</h1>
    <h4><a href="/">网站首页</a></h4>
    <h4><a href="{% url 'users:user_login' %}">用户登录</a></h4>
    <h4><a href="{% url 'users:user_register' %}">用户注册</a></h4>
    <h4><a href="{% url 'users:user_info' %}">个人信息</a></h4>
    <h4><a href="{% url 'store:add' %}">开店</a></h4>
    <h4><a href="{% url 'users:user_logout' %}">用户退出</a></h4>
</body>
</html>